name: global_dependencies
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.3
  flutter_modular: 6.3.2
  flutter_triple: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
