name: ERP

packages:
  - app/
  - core/
  - design_system/
  - l10n/
  - dependencies/*
  - modules/*

scripts:
  gen-l10n:
    run: |
      cd l10n
      flutter gen-l10n
    description: Generate translation files in l10n package

# Install
# dart pub global activate <package>
# dart pub global activate melos
# dart pub global activate fvm
# dart pub global activate full_coverage

# melos bs = flutter pub get
# melos bootstrap = flutter pub get
# melos clean = flutter clean

# Ele baixa os pacotes pra sua maquina

# flutter clean
#   Ele vai "esquecer" onde estão os pacotes, mas eles vão continuar lá

Pasta
  flutter create app
  flutter create -t package core
  flutter create -t package design_system
  flutter create -t package l10n
  Pasta dependencies
    flutter create -t package dev_tools
    flutter create -t package global_dependencies
  Pasta modules
    flutter create -t package auth_module
    flutter create -t package ingredient_module
    flutter create -t package packaging_module
    flutter create -t package stock_module -> Estoque gera Ordem de compra quando um item é adicionado
    flutter create -t package financial_module -> Finalizar Ordens de Compra
  melos.yaml
  pubspec.yaml


# /stock -> StockStore
# /financial -> StockStore

# /stock
# /financial/stock -> StockModule



# DRY - Dont Repeat Yourself
  Estoque - 15 funcionalidades
    OrdemDeCompraEntity
      15 props
  Financial - 1 funcionalidades
    OrdemDeCompraEntity
      3 props
