name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 2.25.4
  firebase_auth: 4.17.4
  global_dependencies:
    path: ../global_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  dev_tools:
    git:
      url: https://github.com/DaniFBN/example_multirepo

flutter:
