arb-dir: lib/src/arbs
template-arb-file: app_pt.arb
output-dir: lib/src/gen
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_untranslated_messages.json
